module.exports = [
  "4CS",
  "@Formula/@Command",
  "ABAP",
  "AIMMS",
  "ALGOL 68",
  "ARM Assembler",
  "ASP",
  "ActionScript3",
  "Actionscript",
  "Ada",
  "Apache",
  "AppleScript",
  "Apt sources.list",
  "AutoCAD/IntelliCAD Lisp",
  "AutoIT",
  "Autohotkey",
  "AviSynth",
  "Awk",
  "Axapta/Dynamics Ax X++",
  "BASCOM AVR",
  "BNF (Backus-Naur form)",
  "Bash",
  "Basic4GL",
  "BibTeX",
  "BlitzBasic",
  "Boo",
  "Brainfuck",
  "C",
  "C (for LoadRunner)",
  "C for Macs",
  "C with WiAPI",
  "C#",
  "C++",
  "C++ with WinAPI",
  "CAD DCL (Dialog Control Language)",
  "CFDG",
  "CIL (Common Intermediate Language)",
  "CMake",
  "COBOL",
  "CSS",
  "ChaiScript",
  "Chapel",
  "Clojure",
  "CoffeeScript",
  "ColdFusion",
  "Cuesheet",
  "D",
  "DCL",
  "DCPU/16 Assembly",
  "DCS",
  "DIV",
  "DOS",
  "Dart",
  "Delphi (Object Pascal)",
  "Delphi Prism (Oxygene)",
  "Diff-output",
  "E",
  "ECMAScript",
  "EZT",
  "Eiffel",
  "Email (mbox/eml/RFC format)",
  "Enerscript",
  "Erlang",
  "Euphoria",
  "F#",
  "Falcon",
  "Formula One",
  "Fortran",
  "FreeBasic",
  "FreeSWITCH",
  "GAMBAS",
  "GDB",
  "GML",
  "GNU Gettext .po/.pot",
  "GNU Octave M-file",
  "Generic Lisp",
  "Genero",
  "Genie",
  "Gnuplot script",
  "Go",
  "Groovy",
  "GwBasic",
  "HQ9+",
  "HTML 4.01 strict",
  "HTML5",
  "Haskell",
  "Haxe",
  "HicEst",
  "INI",
  "INTERCAL",
  "ISPF Panel",
  "Icon",
  "Inno Script",
  "Io",
  "J",
  "Java",
  "Java 5",
  "JavaScript",
  "Job Control Language",
  "KLone with C",
  "KLone with C++",
  "LDIF",
  "LLVM",
  "LOLcode",
  "LaTeX",
  "Liberty BASIC",
  "Lightwave Script",
  "Linden Scripting",
  "Locomotive Basic (Amstrad CPC series)",
  "Logcat",
  "Logtalk",
  "LotusScript",
  "Lua",
  "MMIX Assembler",
  "MOS 6502",
  "MOS 6502 Kick Assembler",
  "MOS 6502 TASM/64TASS",
  "MXML",
  "MagikSF",
  "Make",
  "MapBasic",
  "Matlab M-file",
  "Microchip Assembler",
  "Microsoft Registry Editor",
  "Modula-2",
  "Modula-3",
  "Motorola 68000 Assembler",
  "Motorola 68000 Devpac Assembler",
  "MySQL",
  "Nagios",
  "NetRexx",
  "Nimrod",
  "Nullsoft Scriptable Install System",
  "OCaml (Objective Caml)",
  "Oberon-2",
  "Objeck Programming Language",
  "Objective-C",
  "OpenBSD packet filter",
  "OpenOffice.org Basic",
  "Oracle 11i",
  "Oracle 8",
  "Oracle 9.2 PL/SQL",
  "Oz",
  "PARI/GP",
  "PCRE",
  "PHP",
  "PIC16 Assembler",
  "PL/I",
  "ParaSail",
  "Pascal",
  "Per (forms)",
  "Perl",
  "Perl 6",
  "Pike",
  "Pixel Bender 1.0",
  "Plain Text",
  "PostgreSQL",
  "Postscript",
  "Povray",
  "PowerBuilder (PowerScript)",
  "PowerShell",
  "ProFTPd",
  "Progress",
  "Prolog",
  "Property",
  "ProvideX",
  "PureBasic",
  "Python",
  "Python for S60",
  "QBasic/QuickBASIC",
  "QML",
  "R",
  "RBS Script",
  "RPM Spec",
  "Racket",
  "Rebol",
  "Rexx",
  "Ruby",
  "Ruby (with Ruby on Rails Framework)",
  "Rust",
  "SAS",
  "SCL",
  "SPARK",
  "SPARQL",
  "SQL",
  "Scala",
  "Scheme",
  "SciLab",
  "Smalltalk",
  "Smarty template",
  "StandardML",
  "StoneScript",
  "SystemVerilog IEEE 1800-2009(draft8)",
  "T-SQL",
  "TCL/iTCL",
  "Tera Term Macro",
  "TypoScript",
  "UPC",
  "Unicon",
  "Unoidl",
  "UnrealScript",
  "Urbi",
  "VB.NET",
  "VBScript",
  "VHDL",
  "Vala",
  "Vedit macro language",
  "Verilog",
  "Vim scripting",
  "Visual Basic",
  "Visual FoxPro",
  "Visual Prolog",
  "Whitespace",
  "Whois response (RPSL format)",
  "WinBatch",
  "XBasic",
  "XML",
  "YAML",
  "ZXBasic",
  "ZiLOG Z80 Assembler",
  "asymptote",
  "autoconf",
  "dot",
  "fo",
  "glSlang",
  "jQuery 1.3",
  "mIRC Scripting",
  "newLISP",
  "nginx",
  "ooRexx",
  "q/kdb+",
  "robots.txt",
  "sdlBasic",
  "thinBasic",
  "x86 Assembler",
  "xorg.conf",
];
