version: '3'
services:
  node:
    environment:
      - DB_CONNECTION_URL=mongodb://mongo:27017/test
    restart: always
    build: .
    command: yarn start
    ports:
      - 127.0.0.1:5500:5500
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - 127.0.0.1:28018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: